config/routes.rb
Rails.application.routes.draw do
  root 'tags#index'
  get '/tags/:id' => 'tags#show', as: :tag
  get '/destinations/:id' => 'destinations#show', as: :destination
  get '/destinations/:id/edit' => 'destinations#edit', as: :edit_destination 
  patch '/destinations/:id' => 'destinations#update'

end

app/models/destination.rb
class Destination < ActiveRecord::Base
	belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :destinations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
	def show
    	@destination = Destination.find(params[:id])
  	end

  	def edit 
  		@destination = Destination.find(params[:id]) 
	end

	def update 
  		@destination = Destination.find(params[:id]) 
 	 	if @destination.update_attributes(destination_params) 
    		redirect_to(:action => 'show', :id => @destination.id) 
  		else 
    		render 'edit' 
  		end 
	end

	private 
  		def destination_params 
    		params.require(:destination).permit(:name, :description) 
  		end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def index
		@tags = Tag.all
	end
	
	def show 
  		@tag = Tag.find(params[:id]) 
  		@destinations = @tag.destinations 
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/destinations/edit.html.erb
<div class="header">
  <div class="container">
    <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1tm.svg" width="80">
    <h1>BokenjiKan</h1>
  </div>
</div>

<div class="destination">
  <div class="container">
    <%= image_tag @destination.image %>

    <%= form_for(@destination) do |f| %>
      <%= f.text_field :name %>
      <%= f.text_field :description %>
      <%= f.submit "Update", :class => "btn" %>
    <% end %> 
  </div>
</div>

app/views/destinations/show.html.erb
<div class="header">
  <div class="container">
    <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1tm.svg" width="80">
    <h1>BokenjiKan</h1>
  </div>
</div>

<div class="destination">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <%= image_tag @destination.image %>
        <h2><%= @destination.name %></h2>
        <p><%= @destination.description %></p>
        <%= link_to "Edit", edit_destination_path(@destination) %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  
    <%= yield %>
  

  </body>
</html>

app/views/tags/index.html.erb
<div class="top-bar">
  <div class="title-area">
    <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1tm.svg" width="80">
    <h1 class="subheader">Travel</h1>
  </div>
</div>

<div class="row">  
    <div class="medium-12 columns">
      <% @tags.each do |t| %>
        <div class="medium-4 columns">
        <div class="overlay-container">
          <%= image_tag t.image, class: "img" %>
          <h2 class="overlay"><%= t.title %></h2>
          </div>
          <div class="button">
            <%= link_to "Learn more", tag_path(t), class: "text" %>
          </div>
        </div>
      <% end %>
    
  </div>

app/views/tags/show.html.erb
<div class="top-bar">
  <div class="title-area">
    <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1tm.svg" width="80">
    <h1 class="subheader">Travel</h1>
  </div>
</div>

<div class="row">  
    <div class="medium-12 columns">
    <h2 id="title"><%= @tag.title %></h2>
      <% @destinations.each do |d| %>
      <div class="medium-4 columns">
        <%= image_tag d.image %>
        <h2 id="show"><%= d.name %></h2>
        <p><%= d.description %></p>
      </div>
      <% end %>
        <div class="button">
            <%= link_to "Back", root_path, class: "text" %>
        </div>
    </div>
          
  </div>